### ISSUE TITLE
Jolie Deployer common storage

### ISSUE THREAD

**Issue by klenow** [DM848/srv-jolie-deployer#3]
if having more replicas they should all have the user programs (requested by the cloud_server), meaning some common storage solution is needed

**Comment by joelhandig** [comment]
This turned out to be harder then I thought it would be. For now, I think that this is not important. It's better to only run one instance of jolie-deployer.

**Comment by andersfylling** [comment]
Did u try dpecifying a volume in docker-compose and then running "komposer convert" to generate the k8s files needed for persistant storage?

I did that back on Steffens kluster without any special permissions.

But at worst we can just make the joliedeployer spinn up another instance within the same service

**Comment by joelhandig** [comment]
Managed to find the way to do it!

**Comment by joelhandig** [comment]
This task is now complete. The service disk_server can save and retrieve jolie programs from a persistant storage. File is also deleted when service is unloaded. Not tested automatically, but checked manually
