### ISSUE TITLE
Remove the kubernetes loadbalancer

### ISSUE THREAD

**Issue by klenow** [DM848/srv-jolie-deployer#4]
Remove loadbalancer from user-services (remove the service.yaml + do some consul stuff to register the service)

**Comment by andersfylling** [comment]
I'll setup auto-routing for those in the ACL. 

in order for a service to update it self it needs to re-register using the following payload structure:
```json
{
  "Name": "name<TOKEN_HERE>",
  "Port": 8888,
  "Tags": [
    "unsafe", 
    "token:<TOKEN_HERE>", 
    "owner:userID",
    "jolie-script"
  ],
  "Check": {
    "HTTP": "http://MY_POD_IP:8888/health",
    "Interval": "10s"
  }

}
```

I added a few extra tags to allow permission and make my pattern matching easier.
Remember that the first registration json must have set the [OverrideTags field](https://www.consul.io/api/agent/service.html#enabletagoverride) to true.

Then the above template json can be sent as a PUT request:
`curl --request POST --send-file service.json --url http://consul-node:8500/vi/agent/service/register`.

You should definetly install consul and run a local consul agent to play around with this, if I don't get around to the re-registration part myself.

Start a new consul agent:
`consul agent -dev`

and add `consul-node` to your hosts list to make it really easy to test it locally. `echo "127.0.0.1 consul-node" > /etc/hosts`

**Comment by andersfylling** [comment]
Needed changes:
 - on load; return the token. Maybe no need to wait, as you could rather query the status for a given token?
 - on load; don't create a load balancer, this is now handled in the ACL at the endpoint `/script/<token>`
 - Make sure to use the JDport.ol when communicating from outside the cluster, and the JDport_localhost when querying from inside the cluster
